using System;
using System.Linq;

namespace Euler.Solutions {
    public class Euler45 : IEuler {
        public string Problem {
            get {
                return @"
Project Euler Problem 45

    Triangle, pentagonal, and hexagonal numbers are generated by the following
    formulae:

    Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
    Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
    Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...

    It can be verified that T285 = P165 = H143 = 40755.

    Find the next triangle number that is also pentagonal and hexagonal.

";
            }
        }

        public string Answer {
            get {
                return "The next triangle number that is also pentagonal and hexagonal is {0}"
                    .FormatWith(this.Solve());
            }
        }

        public double Solve() {
            var tlist = 1L.To(99999).Select(x => fnTri(x)).ToList();
            var pset = 1L.To(99999).Select(x => fnPenta(x)).ToHashSet();
            var hset = 1L.To(99999).Select(x => fnHex(x)).ToHashSet();

            foreach (var item in tlist) {
                if (pset.Contains(item) && hset.Contains(item)) {
                    if (item > 40755) {
                        return item;
                    }
                }
            }

            return 0;
        }

        private Func<long, long> fnTri = x => x * (x + 1) / 2;
        private Func<long, long> fnPenta = x => x * (3 * x - 1) / 2;
        private Func<long, long> fnHex = x => x * (2 * x - 1);

    }
}
