using System.Linq;
using Euler.Sequences;

namespace Euler.Solutions {

    public class Euler2 : IEuler {

        public string Problem {
            get {
                return @"
Project Euler Problem 2:

   Each new term in the Fibonacci sequence is generated by adding the 
   previous two terms. By starting with 1 and 2, the first 10 terms 
   will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

   By considering the terms in the Fibonacci sequence whose values do 
   not exceed four million, find the sum of the even-valued terms.

";
            }
        }

        public string Answer {
            get {
                return "The sum of the even-valued terms in a Fibonacci sequence\nnot exceeding 4 million is: {0}"
                    .FormatWith(this.Solve());
            }
        }

        public double Solve() {

            return FibonacciSequence.NewSequence()
                .End(4000000)
                .Where(x => x.IsEven())
                .Sum();

        }
    }
}
